import { Navbar } from "@/components/shared/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "sonner";
import { Providers } from "@/providers/providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
   <html lang="es" suppressHydrationWarning>
  <body className="antialiased ">
    {/* 1. Mover los gradientes aquí para que cubran TODO, incluyendo el área del Navbar */}
    <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-blue-500/10 dark:bg-blue-900/20 blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-indigo-500/10 dark:bg-indigo-900/20 blur-[120px]" />
    </div>

    <Providers>
      <Navbar />
      <main className="pt-16"> 
        {children}
      </main>
      <Toaster 
  position="bottom-right" 
  theme="system" 
  richColors={false}
  toastOptions={{
  
    style: {
      transition: 'all 0.5s ease',
    },
    classNames: {
      
      toast: "group !border-2 rounded-2xl p-4 flex items-center gap-3 backdrop-blur-md !bg-white dark:!bg-slate-950 shadow-lg",
      
      title: "!text-slate-900 dark:!text-white font-bold text-sm",
      description: "!text-slate-500 dark:!text-slate-400 text-xs font-medium",
      
      success: "!border-blue-500/30",
      error: "!border-red-500/30",
      info: "!border-slate-200 dark:!border-slate-800",
    
      icon: "group-data-[type=success]:!text-blue-500 group-data-[type=error]:!text-red-500",
    },
  }}
/>
    </Providers>
</body>
</html>

  );
}
